# /* ---- 💫 https://github.com/JaKooLit 💫 ---- */  
# /* wallust template - colors-hyprland */ 

$background = rgb(121211)
$foreground = rgb(F7FAFB)
$color0 = rgb(3A3A39)
$color1 = rgb(0D0D0C)
$color2 = rgb(2D3336)
$color3 = rgb(4C5A62)
$color4 = rgb(515E66)
$color5 = rgb(56646C)
$color6 = rgb(ADB5B6)
$color7 = rgb(EAEFF0)
$color8 = rgb(A4A8A8)
$color9 = rgb(111210)
$color10 = rgb(3C4448)
$color11 = rgb(667882)
$color12 = rgb(6D7E87)
$color13 = rgb(73858F)
$color14 = rgb(E7F1F3)
$color15 = rgb(EAEFF0)
