# /* ---- 💫 https://github.com/JaKooLit 💫 ---- */  #
# /* wallust template - colors-kitty */

foreground         #F7FAFB
background         #121211
cursor             #999FA1

active_tab_foreground     #121211
active_tab_background     #F7FAFB
inactive_tab_foreground   #F7FAFB
inactive_tab_background   #121211

active_border_color   #F7FAFB
inactive_border_color #121211
bell_border_color     #0D0D0C

color0      #3A3A39
color1		#0D0D0C
color2		#2D3336
color3		#4C5A62
color4		#515E66
color5		#56646C
color6		#ADB5B6
color7		#EAEFF0
color8		#A4A8A8
color9		#111210
color10		#3C4448
color11		#667882
color12		#6D7E87
color13		#73858F
color14		#E7F1F3
color15		#EAEFF0
